name = "directomatic"
workers_dev = true
main = "src/index.ts"
compatibility_date = "2022-11-30"

[build]
command = "npm install && npm run build"

[vars]
GSHEETS_API_ENDPOINT = "https://sheets.googleapis.com/v4/spreadsheets"
CF_API_ENDPOINT = "https://api.cloudflare.com/client/v4"
DEFAULT_DEST_DOMAIN = "https://1904labs.com"
DEFAULT_LOCALE = "en-US"
